---
title: "rmse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## RMSE

Script for calculating RMSE for cyclone and seurat compared to the annotation data. This script requries that you first run "Cell_cycle_prediction.Rmd" modified to save the needed files. 


```{r data}
# read files as tables, actual is the annotated data
actual_buttner <- read.table("/Users/Lovisa Lundeberg/Documents/scrna-cell-cycle/r_scripts/lovisa/actual.txt", header = FALSE, sep = "", dec = ".")
predicted_cyclone_buttner <- read.table("/Users/Lovisa Lundeberg/Documents/scrna-cell-cycle/r_scripts/lovisa/predicted_cyclone.txt", header = FALSE, sep = "", dec = ".")
predicted_seurat_buttner <- read.table("/Users/Lovisa Lundeberg/Documents/scrna-cell-cycle/r_scripts/lovisa/predicted_seurat.txt", header = FALSE, sep = "", dec = ".")

# saving the data from the files as vectors
actual_buttner <- as.vector(unlist(lapply(c(actual_buttner), as.numeric)))
predicted_cyclone_buttner <- as.vector(unlist(lapply(c(predicted_cyclone_buttner), as.numeric)))
predicted_seurat_buttner <- as.vector(unlist(lapply(c(predicted_seurat_buttner), as.numeric)))

```

## Calculating RMSE

```{r rmse}
# function for RMSE
RMSE = function(m, o){
  sqrt(mean((m - o)^2))
}

# calculating RMSE for cyclone and seurat using the data from Buttner et al.
RMSE_cyc_bu <- RMSE(predicted_cyclone_buttner,actual_buttner)
RMSE_seu_bu <- RMSE(predicted_seurat_buttner,actual_buttner)

# calculating RMSE for seurat using the data from Leng et al.
actual_leng <- c(91, 76, 80) #taken from article
seurat_leng <- c(26, 134, 87)

RMSE_seu_le <- RMSE(seurat_leng,actual_leng)

RMSE_seu <- c(RMSE_seu_bu,RMSE_seu_le)
```

```{r plot}
barplot(RMSE_seu, main = "Seurat", xlab ="Data", ylab="RMSE", names.arg=c("Buttner et al.","Leng et al."), border="blue", density=c(10), col=c("purple","purple"))

```