---
title: "sasagawa"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Script for running Sasagawa et al data on Cyclone and Seurat

A small dataset of 23 cells. Annotation G1 8, S 7 and G2M 8.

```{r data}
mypath = "/Users/Lovisa Lundeberg/Documents/scrna-cell-cycle/r_scripts/lovisa/embryonic_data/sasagawa"
setwd(mypath)

# reading in the separate text files and putting them next to each other in a data frame
txt_files_ls = list.files(path=mypath, pattern="*.txt")
txt_files_df <- lapply(txt_files_ls, function(x) {read.table(file = x, header = T, sep ="")})
exprs_sa <- do.call("cbind", lapply(txt_files_df, as.data.frame))

id <- as.data.frame(exprs_sa[,1:2])

exprs_sa <- exprs_sa[ ,-which(names(exprs_sa) %in% c("id", "gene.symbol"))]

```


```{r filter}
# filter out cells with low nDet
nDet <- colSums(exprs_sa)
hist(nDet,n=100)
keep <- which(nDet>4000)

exprs_sa<-exprs_sa[,keep]

#adding ENS id and hgnc symbols to matrix
rownames(exprs_sa) <- paste(id[,1]) 
exprs_sa <- cbind(hgnc_symbol=id[,2],exprs_sa)

```

```{r cyclone, warning=F}
#adding ensembl ids as rownames
#exprs_id <- exprs_an[,-1]
#rownames(exprs_id) <- paste(exprs_an[,1]) 

exprs_sa_id <- data.matrix(exprs_sa[,-1])
mmu.pairs <- readRDS(system.file("exdata", "mouse_cycle_markers.rds", package="scran"))

set.seed(123)
sce_leng <- SingleCellExperiment(assays=list(counts = exprs_sa_id, logcounts = log2(exprs_sa_id+1)))
cc <- cyclone(sce_leng, pairs=mmu.pairs)
table(cc$phase)


cyc_sa_pre <- as.vector(unlist(lapply(c(table(cc$phases)), as.numeric)))

```
```{r Seurat}
# create a seurat object
sdata <- CreateSeuratObject(raw.data = exprs_sa_id, min.cells = 3, min.genes = 200,
    project = "CC",is.expr=1,meta.data=NULL)

sdata <- NormalizeData(sdata)
sdata <- ScaleData(sdata)
sdata <- FindVariableGenes(object = sdata, mean.function = ExpMean, 
                           dispersion.function = LogVMR, x.low.cutoff = 0.2, 
                           x.high.cutoff = 10, y.cutoff = 0.5)

# run PCA
sdata <- RunPCA(object = sdata, pc.genes = sdata@var.genes, do.print = FALSE)  
# predict cell cycle
sdata <- CellCycleScoring(sdata, g2m.genes = cc.genes.mouse$g2m.genes, 
                          s.genes = cc.genes.mouse$s.genes)

table(sdata@meta.data$Phase)

# saving the result as a numeric vector
seu_sa_pre <- c(table(sdata@meta.data$Phase))
seu_sa_pre <- as.vector(unlist(lapply(c(seu_sa_pre), as.numeric)))
```