---
title: "reCAT_run"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load some packages

```{r load, warning=FALSE}
suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(MultiAssayExperiment))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(doParallel))
suppressPackageStartupMessages(library(mclust))
suppressPackageStartupMessages(library(cluster))
suppressPackageStartupMessages(library(TSP))
```

# Load the data 

```{r data}
# load("reCAT_master/data/ola_mES_2i.RData")
cc_data <- readRDS("embryonic_data/EMTAB2805.rds")

# Get tpms at gene level, TPM = (Transcripts Per Kilobase Million), TPM is generated beforehand through
# 1. Divide the read counts by the length of each gene in kilobases. This gives you reads per kilobase (RPK).
# 2. Count up all the RPK values in a sample and divide this number by 1,000,000. This is your per million scaling factor.
# 3. Divide the RPK values by the per million scaling factor. This gives you TPM.
# Assays is a subclass of RangedSummarizedExperiment in which A list or SimpleList of matrix-like elements, or a matrix-like object. 
# All elements of the list must have the same dimensions, and dimension names (if present) must be consistent across elements and 
# with the row names of rowRanges and colData
# Retrieves the gene vs. counts data in TPM
exprs_sa_id <- assays(experiments(cc_data)[["gene"]])[["TPM"]]

# Log transforms the data as get_gest requires log-transformed data 
exprs_sa_id <- log(exprs_sa_id+1)

# Remove spike-ins from expression table,  ERCC = External RNA Controls Consortium (ERCC)
# External RNA-controls to check for variability, ie: not needed for the analysis
ercc <- grep("ERCC",rownames(exprs_sa_id))
exprs_sa_id <- exprs_sa_id[-ercc,]
# Remove the .1 etc from the ensembl gene name
gname <- rownames(exprs_sa_id)
ensname <- gsub("\\.\\d+","",gname)
rownames(exprs_sa_id) <- ensname

# Filter out all cells with a low cell-count
dim(exprs_sa_id)
nDet <- colSums(exprs_sa_id>1)
keep <- which(nDet>4000)
exprs_sa_id <- exprs_sa_id[,keep]
dim(exprs_sa_id)

# Inspect the matrix
indices <- c(1, 20, 33, 44, 64)
exprs_sa_id[indices,indices]
```

# Clears out all genes not present as marker genes

```{r preprocess}

source("reCAT_master/R/get_test_exp.R")
exprs_sa_id <- get_test_exp(exprs_sa_id)
dim(exprs_sa_id)
```

# Orders the data using the TSP algorithm

```{r order}
source("reCAT_master/R/get_ordIndex.R")
# exprs_sa_id = input matrix, 3 = no. threads used for processing, can be increased on cluster
nthread = 3
ordIndex <- get_ordIndex(exprs_sa_id, nthread)
```

# Get cell-cycle scores using the Bayes-scores & Mean-scores algorithm

```{r scores}
source("reCAT_master/R/get_score.R")
score_result <- get_score(t(exprs_sa_id))
score_result$bayes_score
score_result$mean_score
# cat(score_result$bayes_score, file="bayes_score.txt")
# cat(score_result$mean_score, file="mean_score.txt")
```

# Plots the score values 

```{r plot_scores}
source("reCAT_master/R/plot.R")
plot_bayes(score_result$bayes_score, ordIndex)
plot_mean(score_result$mean_score, ordIndex)
```

```{r rdata}
source("reCAT_master/R/get_rdata.R")
rdata <- get_rdata(score_result, ordIndex)
View(rdata)
```

# Finds the start of the cell-cycle for time-series scoring

```{r get_start}
source("reCAT_master/R/get_start.R")
cls_num = 3
cycle_start = get_start(bayes_score = score_result$bayes_score, mean_score = score_result$mean_score, ordIndex = ordIndex, cls_num = cls_num, rdata = rdata, nthread = nthread)
print(cycle_start)
```

```{r get_myord}
source("reCAT_master/R/get_myord.R")
myord = get_myord(cycle_start, ordIndex)
```

# Finds the cell cycle phases

```{r find_phase}
source("reCAT_master/R/get_hmm.R")
hmm_result <- get_hmm_order(bayes_score = score_result$bayes_score, mean_score = score_result$mean_score, ordIndex = ordIndex, cls_num = cls_num, myord = myord, rdata = rdata)

g1_c = sum(hmm_result == 1)
s_c = sum(hmm_result == 2)
g2m_c = sum(hmm_result == 3)
phase_counts = t(data.frame(g1_c, g2m_c, s_c))
write.table(phase_counts,"recat_phase_output.txt",sep="\t",col.names = FALSE, row.names=FALSE)
View(phase_counts)
```